//! The three ERC-8004 registries the hook writes to
//! (docs/decisions/8004-registries-on-stellar.md): the upstream contracts,
//! built from the vendored source in `contracts/vendor/stellar-8004` — the
//! port the local stack deploys — and registered from their own Wasm. The
//! client types below are generated by `contractimport!` from that Wasm's
//! spec, so the calls a test makes are the ones the contracts declare.
//!
//! Build the port before a test that uses this module:
//!
//! ```text
//! cd contracts/vendor/stellar-8004 && stellar contract build --locked
//! ```

use soroban_sdk::{Address, BytesN, Env, String};

use crate::account::{authorize, call, Account};

pub mod identity {
    soroban_sdk::contractimport!(file = "../vendor/stellar-8004/target/wasm32v1-none/release/identity_registry.wasm");
}

pub mod reputation {
    soroban_sdk::contractimport!(file = "../vendor/stellar-8004/target/wasm32v1-none/release/reputation_registry.wasm");
}

pub mod validation {
    soroban_sdk::contractimport!(file = "../vendor/stellar-8004/target/wasm32v1-none/release/validation_registry.wasm");
}

/// The testnet identity registry's `name()` and `symbol()`, which the local
/// stack deploys with as well (the decision record's "Deploy order").
pub const IDENTITY_NAME: &str = "Agent Registry";
pub const IDENTITY_SYMBOL: &str = "AGENT";

/// The three registries, deployed in upstream's order: the identity registry,
/// then the reputation and validation registries bound to it.
pub struct Registries {
    pub owner: Account,
    pub identity: Address,
    pub reputation: Address,
    pub validation: Address,
}

impl Registries {
    pub fn deploy(env: &Env) -> Self {
        let owner = Account::new(env);
        let identity = env.register(
            identity::WASM,
            (owner.address.clone(), String::from_str(env, IDENTITY_NAME), String::from_str(env, IDENTITY_SYMBOL)),
        );
        let reputation = env.register(reputation::WASM, (owner.address.clone(), identity.clone()));
        let validation = env.register(validation::WASM, (owner.address.clone(), identity.clone()));
        Registries { owner, identity, reputation, validation }
    }

    pub fn identity<'a>(&self, env: &'a Env) -> identity::Client<'a> {
        identity::Client::new(env, &self.identity)
    }

    pub fn reputation<'a>(&self, env: &'a Env) -> reputation::Client<'a> {
        reputation::Client::new(env, &self.reputation)
    }

    pub fn validation<'a>(&self, env: &'a Env) -> validation::Client<'a> {
        validation::Client::new(env, &self.validation)
    }

    /// `owner` registers an agent with no URI, signing the call; its id.
    pub fn register_agent(&self, env: &Env, owner: &Account) -> u32 {
        authorize(env, &[owner.sign(&call(env, &self.identity, "register", (&owner.address,)))]);
        self.identity(env).register(&owner.address)
    }

    /// `requester`, the agent's owner, asks `validator` to validate `agent_id`
    /// under `request_hash`, as a provider does before submitting a job the
    /// hook should attest.
    pub fn request_validation(
        &self,
        env: &Env,
        requester: &Account,
        validator: &Address,
        agent_id: u32,
        request_uri: &str,
        request_hash: &BytesN<32>,
    ) {
        let uri = String::from_str(env, request_uri);
        authorize(
            env,
            &[requester.sign(&call(
                env,
                &self.validation,
                "validation_request",
                (&requester.address, validator, agent_id, uri.clone(), request_hash),
            ))],
        );
        self.validation(env).validation_request(&requester.address, validator, &agent_id, &uri, request_hash);
    }
}
